### ISSUE TITLE
Meeting: 2018/02/02  about dgplug documentation

### ISSUE THREAD

**Issue by kushaldas** [dgplug/infrastructure#9]
Please add the agenda items below as comments.

**Comment by kushaldas** [comment]
* Show how to use duckduckgo search
* Add a section about how to search first and then ask questions.
* Talk about user privacy (this should become a complete new chapter in the summer training book).
* Using SSL for IRC
* https://ssd.eff.org discussion.
* Things to add in lym?
* Weekly newsletter idea

**Comment by ghost** [comment]
Since IRC is a crucial part of DGPLUG, several means to connect to the channel should be explained, from quick connection (e.g. via internet browser) to more in-depth explanaition. Many new visitors never (or hardly ever, like me) have used IRC before.
Maybe we could include a sample config of the most often used clients?
Logging may also be a topic worth mentioning.

**Comment by ghost** [comment]
**Summary of meeting at 2018-02-02 dgplug documentation**

During the years of summertraining, some books arose from the questions and wisdom that has been shared in the #dgplug IRC channel. These books should help to address frequently asked question and give a solid base knowledge about linux and FOSS, including related topics (law, privacy, history, community):

- https://summertraining.readthedocs.io/en/latest/
- https://lym.readthedocs.io/en/latest/

The meeting was about
- identifying the gaps in that documentation
- gathering ideas to fill the gaps and make the documentation more comprehensive and attractive especially for newcomers
- gathering ideas to improve communication in IRC
- find volunteers to write the needed tools / documentation

**Initial agenda**

Topics that have been posted beforehand:

- Show how to use duckduckgo search
- Add a section about how to search first and then ask questions.
- Talk about user privacy (this should become a complete new chapter in the summer training book).
- Using SSL for IRC
- https://ssd.eff.org discussion.
- Things to add in lym?
- Weekly newsletter idea

**Summary of collected ideas**

*for the book*

- Chapter on what is dgplug
- Chapter on legal and licenses
- Extend communication chapter with guidelines and how-tos => reference to @mbuf's sessions
- Chapter on blogging
- Chapter on recommended Linux distros
- Some chapters will be outsourced with just a few lines and a link to the comprehensive book.
  - commandline etc. will point to lym
  - history will be outsourced
  - extra reading link to http://www.opsschool.org/en/latest/
  - Mercury chapter will become chapter on VCS with extra reading link to guide on git (by @sayan?)
- Chapter on privacy and daily opsec

*for the IRC channel and infra*

- Conduct sessions based on topic hits in the channel log
- Install a meetbot for tenida, to log ideas and issues on the fly
- add the FAQ url to the channel ENTRYMSG
- put IRC logs in a more readable and browsable format
- have a biweekly newsletter where links, news etc. will be collected

**Results**

- @SaptakS volunteered to take the lead in building front-end for IRC logs
- @jasonbraganza volunteered to write chapter on blogging
- @vivekanand1101, @SaptakS, @jasonbraganza and @schubisu volunteered to take the lead in the newsletter project.
